# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 007fef397c9b5e7274dc52b810924e3239aa57666c8d865db8b021596a6dbb790042dfb64854eba4642e5423b89b38fcf6764e3a79dbafc3d7a1296446022c87

test:
  secret_key_base: d5a6114c5be2789d3142839341a66c99b4aac3d064058ee782f802e8994bfddb915f5a1d0d20edc4e1533cfdf582270c2ec72cd3d0960e833b1d959f5813a751

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
